// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "description": "Simple CLI tools library",
  "name": "Clivo",
  "stack": {
    "nodejs": {
      "outputFile": [
        "src",
        "cinnabar.js"
      ],
      "package": "clivo"
    }
  },
  "version": {
    "major": 0,
    "minor": 1,
    "patch": 0,
    "revision": 1,
    "text": "0.1.0",
    "timestamp": 1718294648
  }
};
